# Generated by Django 6.0.7 on 2026-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='paybill',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='admin_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='admin_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
